name: grappus_skribbl
description: A Grappus implementation of Skribbl
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api:
    path: api
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  game_repository:
    path: packages/game_repository
  services:
    path: packages/services
  intl: ^0.18.0
  lottie: ^2.6.0
  models:
    path: api/packages/models
  player_repository:
    path: api/packages/player_repository
  uuid: ^3.0.7
  get_it: ^7.6.4


dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
